version: "3.9"
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$

  my-service:
    image: arinapavlova/my-service
    build: .
    container_name: my-service
    ports:
      - "8000:8000"